- hosts: all
  tasks:
  - name: install docker
    package:
      name: "{{item}}"
      state: latest
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: ensure docker is installed
    service:
      name: docker
      state: started
      enabled: yes
