- hosts: all
  tasks:
  - name: install docker
    package:
      name: "docker-ce"
      state: latest
  - name: ensure docker is installed
    service:
      name: docker-ce
      state: started
      enabled: yes
